### ISSUE TITLE
Add a warning for the urls cached containing the `:` char

### ISSUE THREAD

**Issue by GianlucaGuarini** [dreipol/vue-fetch-route#3]
Sometimes we cache wrong urls in frontend because of mismatching data between the backend router structure and the frontend vue-fetch-route implementation. It would be nice to know with a warning where the vue-fetch-route has found and cached problematic urls.

Something like this should be enouch:
```js
if (/[:|$|{|}]/.test(url)) {
  console.warn('It seems this URL contains wrong chars, could you please double check it?')
}
```

**Comment by nirazul** [comment]
Fixed via 0.1.3
